// exit code: 42

public const class Test
{
    public fn test(self) -> Self
        => self;

    public fn value(self) -> byte
        => 42;
}

public fn main() -> byte
{
    let t = new Test();
    return t.test().value();
}
